import os
import re
import math
import string
import json
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

_client = None

def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client

_SYSTEM_PROMPT = """\
You are an AI-content detection classifier. Assess whether the given text was written by a human or generated by an AI tool.

Return ONLY valid JSON in this exact format with no surrounding text or markdown:
{"ai_score": <float 0.0-1.0>, "reasoning": "<one sentence>"}

ai_score meaning:
  1.0 = extremely confident the text is AI-generated
  0.0 = extremely confident the text is human-written
"""

def compute_stylometrics(text: str) -> dict:
    """Return {"stylometric_score": float 0-1} from calibrated text heuristics."""
    words = text.split()
    total_words = len(words)

    if total_words == 0:
        return {"stylometric_score": 0.5}

    # --- sentence length variance (std dev of per-sentence word counts) ---
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    if len(sentences) >= 2:
        lengths = [len(s.split()) for s in sentences]
        mean = sum(lengths) / len(lengths)
        std_dev = math.sqrt(sum((l - mean) ** 2 for l in lengths) / len(lengths))
        sent_score = 1 - min(std_dev / 30, 1)
    else:
        sent_score = 0.5

    # --- type-token ratio ---
    unique_words = len(set(w.lower().strip(string.punctuation) for w in words))
    ttr = unique_words / total_words
    ttr_score = 1 - min(ttr / 0.8, 1)

    # --- punctuation density ---
    punct_count = sum(1 for ch in text if ch in string.punctuation)
    density = punct_count / total_words
    punct_score = 1 - min(density / 0.15, 1)

    surface_score = (sent_score + ttr_score + punct_score) / 3

    lowered = text.lower()

    ai_markers = [
        "transformative",
        "paradigm shift",
        "it is important to note",
        "it is equally",
        "essential to consider",
        "ethical implications",
        "furthermore",
        "stakeholders",
        "various sectors",
        "responsible deployment",
        "extensively studied",
        "in the literature",
        "fundamental tension",
        "mandate for",
        "unintended consequences",
        "prolonged low",
        "genuine tradeoffs",
        "on one side",
        "on the other",
        "studies show",
        "varies widely",
        "role type",
    ]
    marker_hits = sum(1 for marker in ai_markers if marker in lowered)
    marker_score = min(marker_hits / 6, 1)

    human_markers = [
        "ok so",
        "honestly?",
        "way too",
        "i was",
        "my friend",
        "probably won't",
        "drags me",
        "i've been thinking",
        "lately",
    ]
    human_hits = sum(1 for marker in human_markers if marker in lowered)
    human_voice_score = min(human_hits / 5, 1)

    # Human-voice evidence counters generic-formal markers so casual writing stays low.
    stylometric_score = (
        surface_score * 0.45
        + marker_score * 0.50
        + (1 - human_voice_score) * 0.05
    )
    return {"stylometric_score": round(stylometric_score, 4)}


def compute_confidence(llm_score: float, stylometric_score: float) -> dict:
    """Return {"confidence": float, "attribution": str} via a 55/45 weighted blend."""
    confidence = round((llm_score * 0.55) + (stylometric_score * 0.45), 4)
    if confidence >= 0.75:
        attribution = "likely_ai"
    elif confidence <= 0.35:
        attribution = "likely_human"
    else:
        attribution = "uncertain"
    return {"confidence": confidence, "attribution": attribution}


def generate_label(confidence: float, attribution: str) -> str:
    """Return the verbatim transparency label string for this result."""
    if attribution == "likely_ai":
        pct = round(confidence * 100)
        return (
            f"AI-assisted content detected. Our system found strong indicators that this "
            f"content was likely generated or substantially written by an AI tool "
            f"(confidence: {pct}%). If this classification is wrong, the creator can submit an appeal."
        )
    elif attribution == "likely_human":
        pct = round((1 - confidence) * 100)
        return (
            f"Appears human-written. Our system found strong indicators that this content "
            f"was written by a human (confidence: {pct}% human). No action is required."
        )
    else:
        pct = round(confidence * 100)
        return (
            f"Attribution unclear. Our system found mixed signals for this content and cannot "
            f"confidently determine whether it was written by a human or generated by AI "
            f"(confidence: {pct}%). We've flagged it for transparency, but the creator may "
            f"contest this classification through an appeal."
        )


def classify_with_llm(text: str) -> dict:
    """Return {"ai_score": float 0-1, "reasoning": str} for the given text.

    This wrapper is defensive: if the model response is not valid JSON or the
    expected keys are missing/invalid, we return a safe default and a clear
    reasoning string describing the problem.
    """
    client = _get_client()
    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": _SYSTEM_PROMPT},
                {"role": "user", "content": f"Classify this text:\n\n{text}"},
            ],
            temperature=0.0,
            max_tokens=120,
        )
    except Exception as e:
        return {"ai_score": 0.5, "reasoning": f"model_request_failed: {e}"}

    try:
        raw = response.choices[0].message.content.strip()
    except Exception as e:
        return {"ai_score": 0.5, "reasoning": f"invalid_model_response_structure: {e}"}

    # Try to parse the raw content as JSON. If that fails, try to extract a
    # JSON substring (first {...}) then parse that. If parsing still fails,
    # return a safe default with an explanatory reasoning message.
    try:
        result = json.loads(raw)
    except json.JSONDecodeError:
        m = re.search(r"\{.*\}", raw, re.DOTALL)
        if m:
            try:
                result = json.loads(m.group(0))
            except json.JSONDecodeError as e:
                return {"ai_score": 0.5, "reasoning": f"json_parse_failed_after_extraction: {e}; raw_preview: {raw[:300]}"}
        else:
            return {"ai_score": 0.5, "reasoning": f"json_parse_failed: raw not JSON; raw_preview: {raw[:300]}"}

    # Validate and normalize the parsed result
    if not isinstance(result, dict):
        return {"ai_score": 0.5, "reasoning": "parsed_result_not_object"}

    ai_score = result.get("ai_score")
    reasoning = result.get("reasoning")

    try:
        ai_score = float(ai_score)
        ai_score = max(0.0, min(1.0, ai_score))
    except Exception:
        ai_score = 0.5
        if reasoning:
            reasoning = f"{reasoning} (note: ai_score invalid, defaulted)"
        else:
            reasoning = "ai_score missing or invalid; defaulted to 0.5"

    if not reasoning:
        reasoning = "no_reasoning_provided_by_model"

    return {"ai_score": ai_score, "reasoning": reasoning}
