import os
import json
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

_client = None

def _get_client():
    global _client
    if _client is None:
        _client = Groq(api_key=os.environ["GROQ_API_KEY"])
    return _client

_SYSTEM_PROMPT = """\
You are an AI-content detection classifier. Assess whether the given text was written by a human or generated by an AI tool.

Return ONLY valid JSON in this exact format with no surrounding text or markdown:
{"ai_score": <float 0.0-1.0>, "reasoning": "<one sentence>"}

ai_score meaning:
  1.0 = extremely confident the text is AI-generated
  0.0 = extremely confident the text is human-written
"""

def classify_with_llm(text: str) -> dict:
    """Return {"ai_score": float 0-1, "reasoning": str} for the given text."""
    client = _get_client()
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {"role": "system", "content": _SYSTEM_PROMPT},
            {"role": "user", "content": f"Classify this text:\n\n{text}"},
        ],
        temperature=0.0,
        max_tokens=120,
    )
    raw = response.choices[0].message.content.strip()
    result = json.loads(raw)
    result["ai_score"] = max(0.0, min(1.0, float(result["ai_score"])))
    return result
